# Generated by Django 3.2.25 on 2025-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='İsim Soyisim')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Banka')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
            ],
        ),
    ]
