# Generated by Django 3.2.25 on 2025-08-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_paymentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_office',
        ),
        migrations.AddField(
            model_name='package',
            name='orprice',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9),
            preserve_default=False,
        ),
    ]
